### ISSUE TITLE
Help debugging github 422

### ISSUE THREAD

**Issue by luisgc93** [sbdchd/squawk-action#5]
I'm currently getting a 422 response from github when adding this github action:
````
Run export SQUAWK_GITHUB_TOKEN=***
20:57:10 [INFO] no config file found
20:57:10 [INFO] pg version: None
20:57:10 [INFO] excluded rules: []
20:57:10 [INFO] assume in a transaction: false
20:57:10 [INFO] checking files
20:57:10 [INFO] reading content from stdin
20:57:10 [INFO] ignoring empty stdin
20:57:10 [INFO] checking file path: db_migrations/migrations.sql
20:57:10 [INFO] generating github comment body
20:57:10 [INFO] using github actions client
20:57:10 [INFO] checking for existing comment
20:57:10 [INFO] creating comment
Upload to GitHub failed: Problem calling GitHub API: https://api.github.com/repos/{repo_name}/issues/{issue_number}/comments: Client Error: 422 Unprocessable Entity
Error: Process completed with exit code 1.
````

I've looked at the gh API docs and the body field is required when doing a POST to create a comment in an issue:
https://docs.github.com/en/rest/issues/comments?apiVersion=2022-11-28#create-an-issue-comment

I've checked the [rust source code](https://github.com/sbdchd/squawk/blob/e6983b4e8a855813100533d46745e8cd8bba26ae/github/src/lib.rs#L33) and the body is required to have a value so I've ruled the possibility of an empty body being sent.

Is there anything else I should check? I've tried both suggested yml file formats:
````
# .github/workflows/lint-migrations.yml
name: Lint Migrations

on: pull_request

jobs:
  lint_migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Find modified migrations
        run: |
          modified_migrations=$(git diff --name-only origin/$GITHUB_BASE_REF...origin/$GITHUB_HEAD_REF 'db_migrations/*.sql')
          echo "$modified_migrations"
          echo "::set-output name=file_names::$modified_migrations"
        id: modified-migrations
      - uses: sbdchd/squawk-action@v1
        with:
          pattern: ${{ steps.modified-migrations.outputs.file_names }}
````

and 
````
# .github/workflows/lint-migrations.yml
name: Lint Migrations

on: pull_request

jobs:
  lint_migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: sbdchd/squawk-action@v1
        with:
          pattern: "db_migrations/*.sql"
          version: "latest"
````

(my .sql migrations just happened to be stored under db_migrations/.*sql)

There's also no .sql files in the main branch, they've been newly generated in the feature branch where I'm adding the squawk action.

My team uses other github actions and the github token permissions seem OK:
````
GITHUB_TOKEN Permissions
  Actions: write
  Checks: write
  Contents: write
  Deployments: write
  Discussions: write
  Issues: write
  Metadata: read
  Packages: write
  Pages: write
  PullRequests: write
  RepositoryProjects: write
  SecurityEvents: write
  Statuses: write
````

Thanks in advance, appreciate any input.
